# EasyPanel Configuration for Hyperlane Warp UI
# Formato docker-compose compatível com EasyPanel

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4091:4091"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=4091
      - HOSTNAME=0.0.0.0
      # Adicione outras variáveis de ambiente necessárias:
      # - NEXT_PUBLIC_WALLET_CONNECT_ID=your-project-id
      # - NEXT_PUBLIC_REGISTRY_URL=https://registry.example.com
      # - SENTRY_AUTH_TOKEN=your-sentry-token
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4091/"]
      interval: 30s
      timeout: 10s
      start_period: 60s
      retries: 3
